// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of tastecheck

package extract

import (
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
)

var fixtures = map[string]string{
	"a.go": `package src

// Hello returns a greeting.
func Hello(name string) string {
	return "hello " + name
}

type T struct{}

func (t T) Value() int { return 1 }

func (t *T) Pointer() {
}

type G[K comparable] struct{}

func (g *G[K]) Get(k K) K { return k }
`,
	"a_test.go": `package src

func helperInTest() {}
`,
	"gen.go": `// Code generated by hand. DO NOT EDIT.

package src

func Generated() {}
`,
	"README.md":        "not go",
	"sub/b.go":         "package sub\n\nfunc B() {}\n",
	"vendor/v/v.go":    "package v\n\nfunc Vendored() {}\n",
	"testdata/t.go":    "package t\n\nfunc InTestdata() {}\n",
	".hidden/h.go":     "package hidden\n\nfunc Hidden() {}\n",
	"_ignored/i.go":    "package ignored\n\nfunc Ignored() {}\n",
	"broken/broken.go": "package broken\n\nfunc (\n",
}

func writeFixtures(t *testing.T) string {
	t.Helper()
	root := t.TempDir()
	for name, content := range fixtures {
		path := filepath.Join(root, name)
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	return root
}

func names(funcs []Function) []string {
	out := make([]string, 0, len(funcs))
	for _, f := range funcs {
		out = append(out, f.Name)
	}
	return out
}

func TestExtractPatterns(t *testing.T) {
	root := writeFixtures(t)

	tests := []struct {
		name     string
		patterns []string
		opts     Options
		want     []string
		wantErr  bool
	}{
		{
			name:     "directory is non-recursive and skips tests and generated files",
			patterns: []string{root},
			want:     []string{"Hello", "(T).Value", "(*T).Pointer", "(*G[K]).Get"},
		},
		{
			name:     "include tests",
			patterns: []string{root},
			opts:     Options{IncludeTests: true},
			want:     []string{"Hello", "(T).Value", "(*T).Pointer", "(*G[K]).Get", "helperInTest"},
		},
		{
			name:     "single file",
			patterns: []string{filepath.Join(root, "sub", "b.go")},
			want:     []string{"B"},
		},
		{
			name:     "recursive skips vendor, testdata, dot and underscore dirs",
			patterns: []string{filepath.Join(root, "sub") + "/...", filepath.Join(root, "a.go")},
			want:     []string{"Hello", "(T).Value", "(*T).Pointer", "(*G[K]).Get", "B"},
		},
		{
			name:     "duplicate patterns are deduplicated",
			patterns: []string{filepath.Join(root, "sub"), filepath.Join(root, "sub", "b.go")},
			want:     []string{"B"},
		},
		{
			name:     "recursive walk hits parse error",
			patterns: []string{root + "/..."},
			wantErr:  true,
		},
		{
			name:     "missing path",
			patterns: []string{filepath.Join(root, "missing")},
			wantErr:  true,
		},
		{
			name:     "non-go file",
			patterns: []string{filepath.Join(root, "README.md")},
			wantErr:  true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := Extract(tt.patterns, tt.opts)
			if tt.wantErr {
				if err == nil {
					t.Fatal("Extract() expected error")
				}
				return
			}
			if err != nil {
				t.Fatalf("Extract() error: %v", err)
			}
			if !reflect.DeepEqual(names(got), tt.want) {
				t.Errorf("Extract() names = %v, want %v", names(got), tt.want)
			}
		})
	}
}

func TestExtractFunctionDetails(t *testing.T) {
	root := writeFixtures(t)
	path := filepath.Join(root, "a.go")

	got, err := Extract([]string{path}, Options{})
	if err != nil {
		t.Fatalf("Extract() error: %v", err)
	}

	hello := got[0]
	want := Function{
		File:      path,
		StartLine: 4,
		EndLine:   6,
		Name:      "Hello",
		Source:    "// Hello returns a greeting.\nfunc Hello(name string) string {\n\treturn \"hello \" + name\n}",
	}
	if !reflect.DeepEqual(hello, want) {
		t.Errorf("Extract()[0] = %+v, want %+v", hello, want)
	}

	pointer := got[2]
	if pointer.StartLine != 12 || pointer.EndLine != 13 {
		t.Errorf("(*T).Pointer lines = %d-%d, want 12-13", pointer.StartLine, pointer.EndLine)
	}
	if !strings.HasPrefix(pointer.Source, "func (t *T) Pointer()") {
		t.Errorf("(*T).Pointer source = %q", pointer.Source)
	}
}
